version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=users
      - JWT_SECRET=mytokensecret
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - stocktracker-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - stocktracker-network

volumes:
  db_data:

networks:
  stocktracker-network:
    driver: bridge

